---

## VM options

vm_start_on_create: "{{ inventory_hostname in groups['provisioned_vms'] }}"
vm_pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
vm_flags: >-
  --graphics vnc,listen=0.0.0.0
  --controller scsi,model=virtio-scsi
  --serial pty
  --parallel pty
  --virt-type kvm
  --memballoon virtio
  --cpu host-passthrough
  --rng /dev/urandom

# Images to pull from for local builds
vm_image_path: '/mnt/rhv/images'
vm_iso_path: '/mnt/rhv/template/iso'

vm_image_data:
  dummy:
    access_user: null
    python_interpreter: null
  centos7:
    url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    path: "{{ vm_image_path }}"
    name: CentOS-7-x86_64-GenericCloud.qcow2
    access_user: 'centos'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python"
    pkgmgr: yum
    base_os: centos
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  centos8:
    url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2
    path: "{{ vm_image_path }}"
    name: CentOS-8-x86_64-GenericCloud.qcow2
    access_user: 'centos'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: yum
    base_os: centos
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  centos8-stream:
    url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20200113.0.x86_64.qcow2
    path: "{{ vm_image_path }}"
    name: CentOS-8-stream-x86_64-GenericCloud.qcow2
    access_user: 'centos'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: yum
    base_os: centos
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  fedora28:
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2
    path: "{{ vm_image_path }}"
    name: Fedora-Cloud-Base-28-1.1.x86_64.qcow2
    access_user: 'fedora'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: dnf
    base_os: fedora
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  fedora30:
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.qcow2
    path: "{{ vm_image_path }}"
    name: Fedora-Cloud-Base-30-1.2.x86_64.qcow2
    access_user: 'fedora'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: dnf
    base_os: fedora
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  rhel7:
    url: "{{ redhat_7_cloud_image_url | default('undefined') }}"
    path: "{{ vm_image_path }}"
    name: rhel-server-7-x86_64-kvm.qcow2
    access_user: 'cloud-user'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python"
    pkgmgr: yum
    base_os: rhel
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  rhel8.0:
    url: "{{ redhat_80_cloud_image_url | default('undefined') }}"
    path: "{{ vm_image_path }}"
    name: rhel-8.0-x86_64-kvm.qcow2
    access_user: 'cloud-user'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: dnf
    base_os: rhel
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  rhel8:
    url: "{{ redhat_8_cloud_image_url | default('undefined') }}"
    path: "{{ vm_image_path }}"
    name: rhel-8-x86_64-kvm.qcow2
    access_user: 'cloud-user'
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: dnf
    base_os: rhel
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  rhel8-ppc64le:
    url: "{{ redhat_8_ppc64le_cloud_image_url | default('undefined') }}"
    path: "{{ vm_image_path }}"
    name: rhel-8-ppc64le-kvm.qcow2
    access_user: 'cloud-user'
    arch: ppc64le
    cloud_init_packages:
      - NetworkManager
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: dnf
    base_os: rhel
    base_packages:
      - vim
      - network-scripts
      - patch
      - git
      - patchutils
      - iptables-services
      - python*-virtualenv
      - tmux
      - OpenIPMI
      - ipmitool
  ubuntu1604:
    url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    path: "{{ vm_image_path }}"
    name: xenial-server-cloudimg-amd64-disk1.img
    access_user: 'ubuntu'
    cloud_init_packages:
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: apt
    base_os: ubuntu
    base_packages: []
  ubuntu1804:
    url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    path: "{{ vm_image_path }}"
    name: bionic-server-cloudimg-amd64.img
    access_user: 'ubuntu'
    cloud_init_packages:
      - qemu-guest-agent
    python_interpreter: "/usr/bin/python3"
    pkgmgr: apt
    base_os: ubuntu
    base_packages: []

# Enable image downloads
vm_image_get: true

# Management network address
#
# Example network setup in inventory
#  vm_preprov_networks:
#    eth1:
#      - 192.168.1.1/22
vm_management_interface: eth1
vm_management_net: "{{ vm_preprov_networks[vm_management_interface][0] }}"

server_cpu_governor: performance
