---

server_system_packages:
  - "@virtualization"
  - "python3-virtualenv"
  - "nfs-utils"
  - "ipmitool"
  - "OpenIPMI"

developer_system_packages:
  - gcc
  - git
  - libselinux-python
  - python-virtualenv
  - tmux
  - vim

tripleo_system_ceph_packages:
  - ceph-ansible
  - util-linux
  - lvm2
