---

server_system_packages:
  - "@virtualization"
  - "python3-virtualenv"
  - "nfs-utils"
  - "ipmitool"
  - "OpenIPMI"

developer_system_packages:
  - git
  - python-virtualenv
  - tmux
  - vim

developer_py_venv_packages:
  - rdopkg
  - glances

# list of hashes which point to patches to pull from online sources
#
#  developer_patches:
#    - url: "https://review.opendev.org/openstack/tripleo-common"
#      refspec: "refs/changes/96/662496/5"
#    - url: "https://review.opendev.org/openstack/tripleo-heat-templates"
#      refspec: "refs/changes/80/662580/1"
#    - url: "https://github.com/openstack/tripleo-ansible"
#      version: "master"
#
developer_patches: []

developer_rebuild_rpms: false

tripleo_system_packages:
  - python-tripleoclient

tripleo_system_ceph_packages:
  - ceph-ansible
  - util-linux
  - lvm2

# Name of the cuurent development release
tripleo_version_dev_enabled: true
tripleo_version: stein
tripleo_ceph_enabled: false
tripleo_loopback_ceph_size: 10
tripleo_ceph_templates: >-
  -e /home/stack/standalone_ceph_parameters.yaml
  -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml

tripleo_cidr: "172.17.24.0/22"
tripleo_job_address: "172.17.25.254"
