---
# Ansible virtualization tools for lab based deployments
# Copyright (C) 2019  Kevin Carter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


- name: Pre-flight Checks
  delegate_to: "{{ vm_virt_host }}"
  block:
    - name: Check VM provisioning network
      command: >-
        virsh net-info provisioning
      ignore_errors: true
      changed_when: false
      register: vm_netinfo_provisioning
      run_once: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['vm_virt_hosts'] }}"

    - name: Check VM external network
      command: >-
        virsh net-info external
      ignore_errors: true
      changed_when: false
      register: vm_netinfo_external
      run_once: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['vm_virt_hosts'] }}"

    - name: Fail when provisioning network is missing
      fail:
        msg: >-
          One of the required networks ['provisioning'] is missing on `{{ item.item }}`.
          Please ensure the network is created and online before continuing.
      when:
        - (item.failed | bool)
      loop: "{{ vm_netinfo_provisioning['results'] }}"
      loop_control:
        label: "{{ item.item }}"
      delegate_to: "{{ item.item }}"
      run_once: true

    - name: Fail when external network is missing
      fail:
        msg: >-
          One of the required networks ['external'] is missing on `{{ item.item }}`.
          Please ensure the network is created and online before continuing.
      when:
        - (item.failed | bool)
      loop: "{{ vm_netinfo_external['results'] }}"
      loop_control:
        label: "{{ item.item }}"
      delegate_to: "{{ item.item }}"
      run_once: true

    - name: Set pre-flight complete fact
      ini_file:
        dest: "/etc/ansible/facts.d/virt_cloud.fact"
        section: "setup"
        option: pre_flight_complete
        value: true
