---
# Ansible virtualization tools for lab based deployments
# Copyright (C) 2019  Kevin Carter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


- name: Setup DSAL monitoring
  hosts: monitors
  any_errors_fatal: true
  gather_facts: true
  become: true
  user: root
  vars:
    hypervisor_destroy_array: false
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install influxdata
      package:
        name: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.7.x86_64.rpm
        state: present

    - name: Start influxdb
      systemd:
        name: influxdb
        state: started
        enabled: true

    - name: Create grafana repo file
      template:
        src: templates/grafana.repo
        dest: /etc/yum.repos.d/grafana.repo

    - name: Install grafana
      package:
        name: grafana
        state: present

    - name: Start grafana
      systemd:
        name: grafana-server
        state: started
        enabled: true

- name: Setup DSAL metric collection
  hosts: "all"
  any_errors_fatal: true
  gather_facts: true
  become: true
  user: root
  vars:
    hypervisor_destroy_array: false
  vars_files:
    - vars/main.yml
  handlers:
    - name: Start telegraf
      systemd:
        name: telegraf
        state: restarted
        enabled: true
  tasks:
    - name: Install telegraf
      package:
        name: https://dl.influxdata.com/telegraf/releases/telegraf-1.11.4-1.x86_64.rpm
        state: present
      notify: Start telegraf

    - name: Create telegraf conf
      template:
        src: templates/telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf
      notify: Start telegraf
