---
# Ansible virtualization tools for lab based deployments
# Copyright (C) 2019  Kevin Carter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


- name: Setup router
  hosts: routers
  any_errors_fatal: true
  gather_facts: true

  vars_files:
    - vars/main.yml
  handlers:
    - name: Enable and start iptables service
      systemd:
        daemon_reload: true
        enabled: true
        name: iptables.service
        state: started
      listen: iptables save
      become: true

    - name: Save persistent rules
      command: /usr/libexec/iptables/iptables.init save
      listen: iptables save
      become: true

  tasks:
    - name: Forward ipv4 traffic
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
        state: present
        reload: true
      become: yes

    - name: Install packages
      package:
        name:
          - iptables
          - iptables-services
        state: present
      become: true

    - name: Masquerade out primary interface
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ ansible_default_ipv4.alias }}"
        jump: MASQUERADE
        comment: NAT
      become: yes
      notify:
        - iptables save
