---
# Ansible virtualization tools for lab based deployments
# Copyright (C) 2019  Kevin Carter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


- name: Run tripleo setup
  hosts: "all"
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/main.yml

  vars:
    deploy_osp: true

  pre_tasks:
    - name: set hostname properly
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 undercloud.{{ ansible_domain }} undercloud localhost localhost.localdomain"
        regexp: '^127\.0\.0\.1'

    - name: Ensure local facts directory exists
      become: true
      file:
        dest: "/etc/ansible/facts.d"
        state: directory
        group: "root"
        owner: "root"
        mode:  "0755"
        recurse: no

    - name: Initialize local facts
      become: true
      ini_file:
        dest: "/etc/ansible/facts.d/tripleo.fact"
        section: "setup"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - option: initialized
          value: true
        - option: tripleo_magic_number
          value: "{{ (24 | random) }}"

    - name: Set instackenv file fact
      set_fact:
        instackenv_file: "{{ lookup('env','HOME') }}/vm-instackenv.yaml"
      when:
        - instackenv_file is undefined

    - name: Copy instackenv into place
      copy:
        src: "{{ instackenv_file }}"
        dest: "{{ ansible_env.HOME }}/vm-instackenv.yaml"

    - name: Read instackenv yaml
      slurp:
        src: "{{ ansible_env.HOME }}/vm-instackenv.yaml"
      register: instack_env

    - name: Set Nodes
      set_fact:
        target_nodes: "{{ (instack_env['content'] | b64decode | from_yaml)['nodes'] }}"

    - name: CA certificate block
      when:
        - redhat_ca_certs_url is defined
      block:
        - name: Check for ca
          stat:
            path: "/etc/pki/ca-trust/source/anchors/{{ redhat_ca_certs_url | basename }}"
          register: rh_it_ca_stat

        - name: Read RH IT CA
          slurp:
            src: "/etc/pki/ca-trust/source/anchors/{{ redhat_ca_certs_url | basename }}"
          register: rh_it_ca
          when:
            - rh_it_ca_stat.stat.exists | bool

        - name: Set rh ca fact
          set_fact:
            ca_certificate_fact: "{{ rh_it_ca['content'] | b64decode }}"
          when:
            - rh_it_ca_stat.stat.exists | bool

  tasks:
    - name: Refresh local facts
      setup:
        gather_subset: "!all"

    - name: Create undercloud config
      template:
        src: templates/undercloud.conf
        dest: "{{ ansible_env.HOME }}/undercloud.conf"
      when:
        - deploy_osp | bool

    - name: Create images directory
      file:
        path: "{{ ansible_env.HOME }}/images"
        state: directory

    - name: Centos package setup
      when:
        - (ansible_distribution | lower) == 'centos'
      block:
        - name: fetch latest repo version
          uri:
            url: https://trunk.rdoproject.org/centos7/current/
            return_content: yes
          register: tripleo_packages

        - name: Set package fact
          set_fact:
            tripleo_package_fact: "{{ (tripleo_packages.content | regex_search('(\\B\"python2-tripleo-repos.*rpm\\b\")', multiline=True)).strip('\"') }}"

        - name: install tripleo repository (centos)
          package:
            name: "https://trunk.rdoproject.org/centos7/current/{{ tripleo_package_fact }}"
            state: present
          become: true

        - name: Set local package facts
          ini_file:
            dest: "/etc/ansible/facts.d/tripleo.fact"
            section: "lab"
            option: "tripleo_package_fact"
            value: "{{ tripleo_package_fact }}"

        - name: Enable tripleo repository (dev)
          command: >-
            tripleo-repos current-tripleo-dev {{ (tripleo_ceph_enabled | bool) | ternary('ceph', '') }}
          changed_when: false
          become: true
          when:
            - tripleo_version_dev_enabled | bool

        - name: Enable tripleo repository (stable)
          command: >-
            tripleo-repos -b {{ tripleo_version }} current {{ (tripleo_ceph_enabled | bool) | ternary('ceph', '') }}
          args:
            creates: "/etc/yum.repos.d/{{ tripleo_version }}-stable.repo"
          changed_when: false
          become: true
          when:
            - not (tripleo_version_dev_enabled | bool)

        - name: Install tripleo packages (py2)
          package:
            name: "python-tripleoclient"
            state: present
          become: true

        - name: Create params yaml
          template:
            src: templates/parameters.yaml.j2
            dest: "{{ ansible_env.HOME }}/parameters.yaml"
      rescue:
        - name: Notice
          debug:
            msg: >-
              The client installation has failed so OSP deployment will be disabled.

        - name: Client install failed
          set_fact:
            deploy_osp: false

    - name: Fedora package setup
      when:
        - (ansible_distribution | lower) == 'fedora'
      block:
        - name: fetch latest repo version
          uri:
            url: https://trunk.rdoproject.org/fedora/current/
            return_content: yes
          register: tripleo_packages

        - name: Set package fact
          set_fact:
            tripleo_package_fact: "{{ (tripleo_packages.content | regex_search('(\\B\"python3-tripleo-repos.*rpm\\b\")', multiline=True)).strip('\"') }}"

        - name: install tripleo repository (fedora)
          package:
            name: "https://trunk.rdoproject.org/fedora/current/{{ tripleo_package_fact }}"
            state: present
          become: true

        - name: Set local package facts
          ini_file:
            dest: "/etc/ansible/facts.d/tripleo.fact"
            section: "lab"
            option: "tripleo_package_fact"
            value: "{{ tripleo_package_fact }}"
          become: true

        - name: Enable tripleo repository (fedora)
          command: >-
            tripleo-repos -d fedora current {{ (tripleo_ceph_enabled | bool) | ternary('ceph', '') }}
          args:
            creates: /etc/yum.repos.d/fedora-stable.repo
          changed_when: false

        - name: Install tripleo packages (py3)
          package:
            name: "python3-tripleoclient"
            state: present
          become: true
      rescue:
        - name: Notice
          debug:
            msg: >-
              The client installation has failed so OSP deployment will be disabled.

        - name: Client install failed
          set_fact:
            deploy_osp: false

    - name: Redhat package setup (internal)
      when:
        - (ansible_distribution | lower) == 'redhat'
      block:
        - name: Fetch params
          uri:
            url: "{{ redhat_puddle_local_images_url }}"
            return_content: yes
          register: compose_details
          when:
            - redhat_puddle_local_images_url is defined

        - name: Create params yaml
          template:
            src: templates/parameters.yaml.j2
            dest: "{{ ansible_env.HOME }}/parameters.yaml"

        - name: Create local_images params
          template:
            src: templates/local_images.yaml.j2
            dest: "{{ ansible_env.HOME }}/local_images.yaml"

        - name: Install tripleo packages (py3)
          package:
            name:
              - python3-tripleoclient
              - vim
              - network-scripts
              - patch
              - git
              - patchutils
              - iptables-services
              - rhosp-director-images
              - rhosp-director-images-ipa
            allow_downgrade: true
            state: latest
          become: true

        - name: Run image unpack command(s)
          shell: |-
            for i in overcloud-full.tar ironic-python-agent.tar; do
              tar xf /usr/share/rhosp-director-images/$i
            done
          args:
            chdir: "{{ ansible_env.HOME }}/images"

      rescue:
        - name: Notice
          debug:
            msg: >-
              The client installation has failed so OSP deployment will be disabled.

        - name: Client install failed
          set_fact:
            deploy_osp: false

    - name: Set global fact
      set_fact:
        deploy_osp: "{{ deploy_osp }}"

    - name: Set local ceph facts
      ini_file:
        dest: "/etc/ansible/facts.d/tripleo.fact"
        section: "lab"
        option: "tripleo_ceph_enabled"
        value: "{{ tripleo_ceph_enabled }}"
      become: true

    - name: System block
      become: true
      block:
        - name: Add the br-netfilter module
          modprobe:
            name: br-netfilter
            state: present

        - name: make module persistent
          lineinfile:
            path: /etc/modprobe.d/netfilter.conf
            line: options br-netfilter
            owner: root
            group: root
            mode: '0644'
            create: true

        - name: Create swap space
          command: dd if=/dev/zero of=/swapfile bs=1M count=2048
          register: mkswap_file
          args:
            creates: /swapfile

        - name: set permissions on swap file
          file:
            path: /swapfile
            mode: 0600

        - name: format swap file
          command: mkswap /swapfile
          when:
            - mkswap_file is changed

        - name: add to fstab
          lineinfile:
            dest: /etc/fstab
            regexp: "/swapfile"
            line: "/swapfile none swap sw 0 0"

        - name: turn on swap
          command: swapon /swapfile
          when:
            - mkswap_file is changed

        - name: set swapiness
          sysctl:
            name: vm.swappiness
            value: "10"
