# Ansible cloud tools for lab based deployments
# Copyright (C) 2019  Kevin Carter
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


- name: Group vm job target node
  hosts: localhost
  connection: local
  any_errors_fatal: true
  gather_facts: true
  user: root
  tags:
    - always
  tasks:
    - name: Check for required hostvars
      fail:
        msg: >-
          The required variable `vm_job_target` is undefined. Define the option in order to continue.
      when:
        - vm_job_target is undefined

    - name: Check for required hostvars
      fail:
        msg: >-
          The required variable `vm_job_user` is undefined. Define the option in order to continue.
      when:
        - vm_job_user is undefined

    - name: Create in-memory vm_virt_hosts group
      add_host:
        name: "{{ hostvars[vm_job_target]['vm_virt_host'] }}"
        groups: vm_virt_host
      changed_when: false

    - name: Get IP address
      shell: >-
        virsh domifaddr {{ vm_job_target }} --source agent | grep -v 'lo' | grep 'ipv4'
      register: _vm_ip
      changed_when: false
      until: _vm_ip.rc == 0
      retries: 72
      delay: 2
      delegate_to: "{{ hostvars[vm_job_target]['vm_virt_host'] }}"

    - name: Set vm ip information
      set_fact:
        vm_ip: "{{ _vm_ip.stdout.split()[3].split('/')[0] }}"

    - name: Create in-memory vm_target group
      add_host:
        name: "{{ vm_job_target }}"
        groups: targets,vm_target
        ansible_host: "{{ vm_ip }}"
        ansible_user: "{{ vm_job_user }}"
      changed_when: false


# These playbooks use the "targets" group to control deployment nodes.
# All of these playbooks will control flow using user input variables.
- import_playbook: vm-update.yml
- import_playbook: tripleo-setup.yml
- import_playbook: tripleo-standalone-setup-ceph.yml
- import_playbook: tripleo-developer-packages.yml


- name: Run updates
  hosts: "vm_target"
  any_errors_fatal: true
  gather_facts: true
  become: true
  tasks:
    - name: Setup basic standalone deployment
      template:
        src: "standalone_parameters.yaml.j2"
        dest: "/home/stack/standalone_parameters.yaml"
        owner: stack
        group: stack

    - name: Run standalone command(s)
      shell: "{{ item }}"
      with_items:
        - tmux new-session -d -s standalone -n standalone || true
        - tmux new-window -n deploy -t 0 || true
        - tmux new-window -n glances -t 1 || true
        - tmux select-window -t 0
        - tmux send-keys "su - stack" C-m
        - tmux send-keys "openstack tripleo container image prepare default
                          --output-env-file containers-prepare-parameter.yaml" C-m
        - tmux send-keys "sudo openstack tripleo deploy
                          --templates
                          --local-ip={{ tripleo_job_address }}/{{ tripleo_cidr | ipaddr('prefix') }}
                          -r /usr/share/openstack-tripleo-heat-templates/roles/Standalone.yaml
                          -e /usr/share/openstack-tripleo-heat-templates/environments/standalone/standalone-tripleo.yaml
                          -e /home/stack/containers-prepare-parameter.yaml
                          -e /home/stack/standalone_parameters.yaml
                          {{ (tripleo_ceph_enabled | bool) | ternary(tripleo_ceph_templates, '') }}
                          --output-dir /home/stack
                          --standalone" C-m
        - tmux select-window -t 1
        - tmux send-keys "/opt/rdo/bin/glances --disable-autodiscover --diskio-iops --diskio-show-ramfs --enable-irq" C-m
        - tmux select-window -t 0

    - name: Build notice
      debug:
        msg: >-
          Stack creation has started. Connect to the system `{{ ansible_host }}` as `{{ vm_job_user }}` and
          change user to `stack`. When ready, you can monitor the installation progress via the `standalone`
          tmux session.
